name: info (reusable)
on:
  workflow_call:
  workflow_dispatch:
jobs:
  debug_info:
    runs-on: ubuntu-latest
    if: (always() && $GSAI_CICD_INFO && $GSAI_CICD_INFO == "true") || false
    env:
      GSAI_CICD_DEBUG:
    steps:
    - uses: actions/checkout@v4.1.0
    - run: |
        echo "Debug Job Running..."
        echo "CI_COMMIT_BRANCH: ${{ github.ref }}"
        echo "CI_MERGE_REQUEST_ID: ${{ github.event.pull_request.number }}"
        echo "CI_DEBUG_TRACE: $CI_DEBUG_TRACE"
        printenv | sort
