name: nodejs (reusable)
on:
  workflow_call:
  workflow_dispatch:
jobs:
  unit_test:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    env:
      SKIP_TEST: ${SKIP_TEST:-"FALSE"}
    steps:
    - uses: actions/checkout@v4.1.0
    - run: npm config set @scope:registry https://gitlab.com/api/v4/packages/npm/
    - run: npm add jest -g
    - run: echo "Install dependencies and running unit test"
    - run: cd ./frontend
    - run: npm ci
    - run: npm run test
#     # 'artifacts.junit' was not transformed because there is no suitable equivalent in GitHub Actions
  build:
    needs: unit_test
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
    - run: npm config set @scope:registry https://gitlab.com/api/v4/packages/npm/
    - run: npm add babel jest -g
    - run: echo "Install dependencies and build project"
    - run: npm ci
    - run: npm run build
#     # 'artifacts.junit' was not transformed because there is no suitable equivalent in GitHub Actions
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
        path: dist/*
  publish_package:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
    - run: echo " *** Publish build artifacts to GitLab Artifactory Registry *** "
    - run: echo "@scope:registry=https://${{ github.server_url }}/api/v4/projects/${{ github.repository }}/packages/npm/" > .npmrc
    - run: echo "//${{ github.server_url }}/api/v4/projects/${{ github.repository }}/packages/npm/:_authToken=${{ github.token }}" >> .npmrc
    - run: npm publish
