name: release_nodejs (reusable)
on:
  workflow_call:
  workflow_dispatch:
jobs:
  noop_version_passthrough:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    if: (always() && $VERSION)
    steps:
    - uses: actions/checkout@v4.1.0
    - run: echo "VERSION=$VERSION" >> release.env
    - run: echo "PROJECT_NAME=${{ github.event.repository.name }}" >> release.env
#     # 'artifacts.dotenv' was not transformed because there is no suitable equivalent in GitHub Actions
  prerelease_tag:
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    if: # Unable to map conditional expression to GitHub Actions equivalent
#         !($VERSION) || !(${{ github.ref }}) || (always() && ${{ github.ref }} == $CI_DEFAULT_BRANCH) || (always() && ${{ github.ref }} =~ /^patch-/) || (always() && ${{ github.ref }} =~ /^staging/) || (always() && ${{ github.ref }} =~ /^release\/*/) || (always() && ${{ github.event_name }} == 'merge_request_event' && ( ${{ github.event.pull_request.base.ref }} =~ /^patch-/ || ${{ github.event.pull_request.base.ref }} =~ /^staging/ || ${{ github.event.pull_request.base.ref }} =~ /^release\/*/ || ${{ github.event.pull_request.base.ref }} == $CI_DEFAULT_BRANCH )) || false
    steps:
    - uses: actions/checkout@v4.1.0
    - run: echo "Preparing"
    - run: export DEBIAN_FRONTEND=noninteractive
    - run: apt update
    - run: apt-get install -y git openssl
    - run: git config --system user.email "build.server@growthsphere.ai"
    - run: git config --system user.name "build-server"
    - run: mkdir -p ~/.ssh
    - run: echo -n "$DEPLOY_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - run: chmod 600 ~/.ssh/id_rsa
    - run: ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - run: chmod 644 ~/.ssh/known_hosts
    - run: "if [[ \"${{ github.ref }}\" == \"${CI_DEFAULT_BRANCH}\" ]]\n  then \n    npm version minor --no-git-tag-version\n    VERSION=`npm pkg get version | tr -d '\"'`\nelif [[ \"${{ github.ref }}\" == patch* ]]\n  then \n    npm version patch --no-git-tag-version\n    VERSION=`npm pkg get version | tr -d '\"'`\nelif [[ \"${{ github.ref }}\" == staging ]]\n  then \n    npm version patch --no-git-tag-version\n    MAJOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f1`\n    MINOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f2`\n    PATCH=`npm pkg get version | tr -d '\"' | cut -d '.' -f3`\n    ALPHA=\"\"\n    VERSION=\"${MAJOR}.${MINOR}.${PATCH}${ALPHA}\"\nelif [[ \"${{ github.ref }}\" == release/* ]]\n  then \n    npm version patch --no-git-tag-version\n    MAJOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f1`\n    MINOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f2`\n    PATCH=`npm pkg get version | tr -d '\"' | cut -d '.' -f3`\n    RELEASE=r\n    DATE=`date  \"+%y%m\"`\n    STRING=S\n    VERSION=\"${MAJOR}.${MINOR}.${PATCH}-${RELEASE}${DATE}-${STRING}.${PATCH}\"\nelse \n    npm version prepatch --no-git-tag-version\n    VERSION=`npm pkg get version | tr -d '\"'`\nfi\nPROJECT_NAME=`npm pkg get name |tr -d '\"'| cut -d '/' -f2`\necho \"Current Job $PROJECT_NAME $VERSION\"\necho \"VERSION=$VERSION\" >> release.env\necho \"PROJECT_NAME=$PROJECT_NAME\" >> release.env\necho \"Current Job $PROJECT_NAME $VERSION\"\n"
#     # 'artifacts.dotenv' was not transformed because there is no suitable equivalent in GitHub Actions
  release:
    needs:
    - noop_version_passthrough
    - prerelease_tag
    runs-on: ubuntu-latest
    container:
      image: node:20.15.1
    if: # Unable to map conditional expression to GitHub Actions equivalent
#         !($VERSION) || !(${{ github.ref }}) || (always() && ${{ github.ref }} == $CI_DEFAULT_BRANCH) || (always() && ${{ github.ref }} =~ /^patch-/) || (always() && ${{ github.ref }} =~ /^staging/) || (always() && ${{ github.ref }} =~ /^release\/*/) || false
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
      with:
        name: prerelease_tag
    - uses: actions/download-artifact@v4.1.0
      with:
        name: noop_version_passthrough
    - run: export DEBIAN_FRONTEND=noninteractive
    - run: apt update
    - run: apt-get install -y git openssl
    - run: git config --system user.email "build.server@growthsphere.ai"
    - run: git config --system user.name "build-server"
    - run: mkdir -p ~/.ssh
    - run: echo -n "$DEPLOY_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - run: chmod 600 ~/.ssh/id_rsa
    - run: ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - run: chmod 644 ~/.ssh/known_hosts
    - run: "echo \"Preparing $PROJECT_NAME $VERSION\"\n      if [[ \"${{ github.ref }}\" == \"${CI_DEFAULT_BRANCH}\" ]]\n  then \n    npm version minor --no-git-tag-version\n    VERSION=`npm pkg get version | tr -d '\"'`\nelif [[ \"${{ github.ref }}\" == patch* ]]\n  then \n    npm version patch --no-git-tag-version\n    VERSION=`npm pkg get version | tr -d '\"'`\nelif [[ \"${{ github.ref }}\" == staging ]]\n  then \n    npm version patch --no-git-tag-version\n    MAJOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f1`\n    MINOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f2`\n    PATCH=`npm pkg get version | tr -d '\"' | cut -d '.' -f3`\n    ALPHA=\"\"\n    VERSION=\"${MAJOR}.${MINOR}.${PATCH}${ALPHA}\"\nelif [[ \"${{ github.ref }}\" == release/* ]]\n  then \n    npm version patch --no-git-tag-version\n    MAJOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f1`\n    MINOR=`npm pkg get version | tr -d '\"' | cut -d '.' -f2`\n    PATCH=`npm pkg get version | tr -d '\"' | cut -d '.' -f3`\n    RELEASE=r\n    DATE=`date  \"+%y%m\"`\n    STRING=S\n    VERSION=\"${MAJOR}.${MINOR}.${PATCH}-${RELEASE}${DATE}-${STRING}.${PATCH}\"\nelse \n    npm version prepatch --no-git-tag-version\n    VERSION=`npm pkg get version | tr -d '\"'`\nfi\ngit add package.json package-lock.json\ngit commit -m \"update application version\"\ngit push -o ci.skip git@${{ github.server_url }}:${{ github.repository_owner }}/${{ github.event.repository.name }}.git HEAD:${{ github.ref }}\necho \"VERSION=$VERSION\" >> release.env\necho \"PROJECT_NAME=$PROJECT_NAME\" >> release.env\necho \"CI_COMMIT_SHA=$(git rev-parse HEAD)\" >> release.env\n"
  apply_tag:
    needs: release
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/gitlab-org/release-cli:latest
    if: # Unable to map conditional expression to GitHub Actions equivalent
#         !($VERSION) || !(${{ github.ref }}) || ${{ github.ref }} == $CI_DEFAULT_BRANCH || ${{ github.ref }} =~ /^patch-/ || ${{ github.ref }} =~ /^staging/ || ${{ github.ref }} =~ /^release\/*/
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
      with:
        name: prerelease_tag
    - uses: actions/download-artifact@v4.1.0
      with:
        name: noop_version_passthrough
    - run: echo "Releasing build ${VERSION}"
    - uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: v$VERSION
        target_commitish: "${{ github.sha }}"
        body: v$VERSION
